#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
VERSION=$(git  describe --tags  --exact-match --abbrev=0)
echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-args P_VERSION=${VERSION} \
             -t $IMAGE_NAME .
