#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
VERSION=$(git  describe --tags --abbrev=0)
echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git  describe --tags --abbrev=0` \
             --build-arg P_VERSION=`git tag | tail -1` \
             -t $IMAGE_NAME .
